name: rich_codex

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  rich_codex:
    strategy:
      matrix:
        python-version: ["3.10"]
        poetry-version: ["1.1.14"]
        os: [ubuntu-latest]
        
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      # Note - can swap order of setup-python and install poetry if there
      # is difficulty with python version, though this in turn will require
      # you to figure out an alternative method of cacheing.
      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - name: Install package
        run: poetry install
      - name: Make a copy of the argument parser without imports
        run: grep -v "def call_" -A 6 sat/sat.py > .github/tmp/sat_codex.py && chmod +x .github/tmp/sat_codex.py
      - name: Generate terminal images with rich-codex
        uses: ewels/rich-codex@v1
        with:
          commit_changes: "true"
